function dq1 = eom_grnd_roll_CS_U(t,in2,in3,U,A,Omega)
%eom_grnd_roll_CS
%    DQ1 = eom_grnd_roll_CS(T,IN2,IN3,Tau)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Apr-2022 13:38:42
k = ceil(1000*t);
if k==0
    Tau = U(1)+A*sin(Omega*t);
else
    Tau = U(k)+A*sin(Omega*t);
end


C_p = in3(9,:);
C_s = in3(8,:);
C_w = in3(10,:);
I_xx = in3(1,:);
I_yy = in3(2,:);
I_zz = in3(3,:);
M = in3(6,:);
b = in3(5,:);
g = in3(7,:);
h = in3(4,:);
psi = in2(3,:);
psi_dot = in2(4,:);
theta_dot = in2(2,:);
u = in2(1,:);
t2 = cos(psi);
t3 = sin(psi);
t4 = I_yy.^2;
t5 = M.^2;
t6 = M.^3;
t7 = b.^2;
t8 = b.^3;
t9 = h.^2;
t10 = h.^3;
t12 = psi.*2.0;
t13 = psi_dot.^2;
t14 = theta_dot.^2;
t15 = I_xx.*I_yy;
t11 = t9.^2;
t16 = t2.^2;
t17 = t2.^3;
t19 = sin(t12);
t20 = t3.^3;
t21 = I_xx.*M.*t7;
t22 = I_yy.*M.*t9;
t26 = t5.*t7.*t9;
t18 = t16.^2;
t23 = t15.*t16;
t24 = I_xx.*I_zz.*t16;
t27 = t16.*t22;
t28 = I_zz.*M.*t9.*t16;
t30 = t16.*t26;
t25 = -t23;
t29 = -t27;
t31 = -t30;
t32 = t15+t21+t22+t24+t25+t26+t28+t29+t31;
t33 = 1.0./t32;
et1 = C_s.*t15.*u+C_s.*t21.*u+C_s.*t22.*u+C_s.*t24.*u+C_s.*t25.*u+C_s.*t26.*u+C_s.*t28.*u+C_s.*t29.*u+C_s.*t31.*u-I_xx.*t5.*t8.*t14+Tau.*t3.*t5.*t10-b.*t6.*t11.*t13-b.*t6.*t11.*t14-t6.*t8.*t9.*t14-M.*b.*t14.*t15+M.*b.*t14.*t23-M.*b.*t14.*t24+C_s.*t5.*t11.*u+C_s.*I_xx.*M.*t9.*u+I_xx.*M.*Tau.*h.*t3-I_xx.*b.*t5.*t9.*t13-I_xx.*b.*t5.*t9.*t14-I_yy.*b.*t5.*t9.*t14+C_w.*t3.*t5.*t10.*theta_dot-C_s.*t5.*t11.*t16.*u+b.*g.*t2.*t6.*t10-b.*g.*t6.*t10.*t17+b.*t6.*t11.*t13.*t16+b.*t6.*t11.*t14.*t16.*2.0-b.*t6.*t11.*t14.*t18+t6.*t8.*t9.*t14.*t16+b.*t6.*t10.*t20.*theta_dot.*u-psi_dot.*t2.*t6.*t7.*t10.*theta_dot.*2.0;
et2 = psi_dot.*t6.*t7.*t10.*t17.*theta_dot.*2.0+C_w.*I_xx.*M.*h.*t3.*theta_dot-C_s.*I_xx.*M.*t9.*t16.*u-(C_p.*b.*psi_dot.*t5.*t9.*t19)./2.0+I_xx.*b.*t5.*t9.*t13.*t16+I_xx.*b.*t5.*t9.*t14.*t16+I_yy.*b.*t5.*t9.*t14.*t16.*2.0-I_yy.*b.*t5.*t9.*t14.*t18-I_zz.*b.*t5.*t9.*t14.*t16.*2.0+I_zz.*b.*t5.*t9.*t14.*t18-I_zz.*psi_dot.*t2.*t5.*t10.*theta_dot.*2.0-I_xx.*I_zz.*M.*h.*psi_dot.*t2.*theta_dot.*2.0+I_xx.*b.*h.*t3.*t5.*theta_dot.*u-I_xx.*h.*psi_dot.*t2.*t5.*t7.*theta_dot.*2.0;
et3 = C_p.*I_yy.*psi_dot.*-2.0+t4.*t14.*t19+t14.*t19.*t22-t13.*t19.*t26-t3.*t4.*t14.*t17.*2.0-t3.*t14.*t17.*t22.*2.0-I_zz.^2.*t3.*t14.*t17.*2.0+C_p.*I_yy.*psi_dot.*t16.*2.0-C_p.*I_zz.*psi_dot.*t16.*2.0-C_p.*M.*psi_dot.*t7.*2.0-I_yy.*I_zz.*t14.*t19+I_yy.*M.*g.*h.*t20.*2.0+I_zz.*M.*g.*h.*t3.*2.0-I_zz.*M.*g.*h.*t20.*2.0+M.*Tau.*b.*h.*t2.*2.0+I_yy.*I_zz.*t3.*t14.*t17.*4.0+I_yy.*M.*t7.*t14.*t19-I_zz.*M.*t7.*t14.*t19+g.*h.*t3.*t5.*t7.*2.0+C_w.*M.*b.*h.*t2.*theta_dot.*2.0+C_s.*M.*b.*t9.*t19.*u-I_yy.*M.*h.*t2.*theta_dot.*u.*2.0+I_yy.*M.*h.*t17.*theta_dot.*u.*2.0-I_zz.*M.*h.*t17.*theta_dot.*u.*2.0+I_zz.*M.*t3.*t9.*t14.*t17.*2.0+I_yy.*M.*b.*h.*psi_dot.*t3.*theta_dot.*4.0-I_yy.*M.*b.*h.*psi_dot.*t20.*theta_dot.*4.0;
et4 = I_zz.*M.*b.*h.*psi_dot.*t3.*theta_dot.*-4.0+I_zz.*M.*b.*h.*psi_dot.*t20.*theta_dot.*4.0;
dq1 = [-(t33.*(et1+et2))./M;-t33.*(I_xx.*Tau+C_w.*I_xx.*theta_dot+M.*Tau.*t9+psi_dot.*t15.*t19.*theta_dot+psi_dot.*t19.*t22.*theta_dot+C_w.*M.*t9.*theta_dot+C_s.*I_xx.*h.*t3.*u+I_xx.*M.*b.*theta_dot.*u-I_xx.*I_zz.*psi_dot.*t19.*theta_dot+C_s.*M.*t3.*t10.*u+(b.*g.*t5.*t9.*t19)./2.0-b.*t3.*t5.*t10.*t13-b.*t5.*t10.*t14.*t20+b.*t5.*t9.*theta_dot.*u-b.*t5.*t9.*t16.*theta_dot.*u-C_p.*M.*b.*h.*psi_dot.*t2-I_xx.*M.*b.*h.*t3.*t13-I_xx.*M.*b.*h.*t3.*t14+I_yy.*M.*b.*h.*t3.*t14-I_yy.*M.*b.*h.*t14.*t20-I_zz.*M.*b.*h.*t3.*t14+I_zz.*M.*b.*h.*t14.*t20-I_zz.*M.*psi_dot.*t9.*t19.*theta_dot);psi_dot;(t33.*(et3+et4))./2.0];
