function dq2 = eom_CS(t,in2,in3,Tau)
%eom_CS
%    DQ2 = eom_CS(T,IN2,IN3,Tau)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    15-Mar-2023 17:00:39

C_s = in3(8,:);
C_w = in3(10,:);
I_zz = in3(3,:);
M = in3(6,:);
b = in3(5,:);
theta = in2(4,:);
theta_dot = in2(5,:);
u = in2(3,:);
t2 = cos(theta);
t3 = sin(theta);
dq2 = [t2.*u-b.*t3.*theta_dot;t3.*u+b.*t2.*theta_dot;b.*theta_dot.^2-(C_s.*u)./M;theta_dot;-(Tau+C_w.*theta_dot+M.*b.*theta_dot.*u)./(I_zz+M.*b.^2)];
