function dq2 = eom_CS(t,in2,in3,in4)
%EOM_CS
%    DQ2 = EOM_CS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-Apr-2022 20:30:13

A = in4(1,:);
C_s = in3(8,:);
C_w = in3(10,:);
I_zz = in3(3,:);
M = in3(6,:);
Omega = in4(2,:);
b = in3(5,:);
theta = in2(4,:);
theta_dot = in2(5,:);
u = in2(3,:);
t2 = cos(theta);
t3 = sin(theta);
dq2 = [t2.*u-b.*t3.*theta_dot;t3.*u+b.*t2.*theta_dot;b.*theta_dot.^2-(C_s.*u)./M;theta_dot;-(C_w.*theta_dot+A.*sin(Omega.*t)+M.*b.*theta_dot.*u)./(I_zz+M.*b.^2)];
